PROJECT=jdksavdecc-cpp
PROJECT_NAME=jdksavdecc-cpp
PROJECT_VERSION?=20130106
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=ISC
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2013
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://jdksavdecc-cpp.statusbar.com/
PROJECT_IDENTIFIER=org.statusbar.jdksavdecc-cpp
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

CONFIG_TOOLS=

